enable open_curly_linter in .lintr
jimhester/lintr pull request #613
Opened 2020-11-28 22:39 UTC by MichaelChirico

There are already no lints for this linter, we just need to enable it in the options:

```
lintr::lint_package(linters = lintr::open_curly_linter)
# returns nothing
```

2020-11-28 22:49 UTC, AshesITR commented
This is already part of the default linters, no need to manually add it.

2020-11-28 23:07 UTC, AshesITR requested changes

2020-11-28 23:07 UTC, AshesITR commented on .lintr
> +   open_curly_linter,
you can just delete the line. It will be enabled through `with_defaults()`

2020-11-29 00:33 UTC, MichaelChirico commented
Hmm, the linter bot seems to have found lints that the command in the issue did not:

```
lintr::lint_package(linters = lintr::open_curly_linter)
```

This also didn't detect those lints that the bot found:

```
for (f in list.files()) print(lintr::lint(f, lintr::open_curly_linter))
```

The lints look correct though, any idea?

2020-11-29 00:55 UTC, MichaelChirico commented
Well, I can reproduce locally with this at least:

```
Rscript -e "lintr::lint_package('.')"
```

with the new settings. I'll edit the issue descriptions...

2020-11-29 09:18 UTC, AshesITR approved these changes

2020-11-29 09:49 UTC, merged