coverage tests for zzz.R
jimhester/lintr pull request #629
Opened 2020-11-29 23:27 UTC by MichaelChirico

- `named_list` is unused in R/, so deleted
`str.lintr_function` won't be called unless we `@export` it to get it registered as S3. Of course, given that it hasn't been used till now, the other option is to just delete this function; LMK.

2020-11-30 11:41 UTC, AshesITR commented
@jimhester do you remember a purpose for `str.lintr_function()`?
If not, I'd vote for deletion.

2020-11-30 14:23 UTC, jimhester commented
You can delete it.

2020-11-30 14:51 UTC, AshesITR approved these changes

2020-11-30 17:03 UTC, AshesITR approved these changes

2020-11-30 17:03 UTC, AshesITR commented on R/utils.R
> +# nocov start used in .onLoad which is nocov
rot() could still be tested, no?
```
expect_identical(
  rot(c(letters, LETTERS, " ", "'")),
  c(letters[14L:26L], LETTERS, " ", "'", letters[1L:13L])
)
```

2020-11-30 17:04 UTC, AshesITR requested changes
Please add a test for `rot()` instead of `# nocov`

2020-11-30 20:11 UTC, MichaelChirico commented
I don't see a way to test `rot` without exposing the private method, is all -- I was recently pointed to

https://stackoverflow.com/questions/105007/should-i-test-private-methods-or-only-public-ones

so I've become more hesitant about testing things that we can't get to directly... if the intention is to get to 100% on covr then that's also fine. any thoughts?

2020-11-30 20:29 UTC, AshesITR commented
I'm thinking a test wouldn't hurt as the public interface using the code is # nocov'd (`.onLoad`)
(and if we did somehow manage to test `.onLoad`, that would also produce full coverage for `rot()` without a separate test)
So aiming for 100% coverage where practical would be my default go-to.

No strong opinon on this instance though. Do as you see fit, the rest of the diff looks good to me - approving.

2020-11-30 20:29 UTC, AshesITR submitted a review, later dismissed

2020-12-01 05:44 UTC, AshesITR approved these changes

2020-12-01 16:58 UTC, merged

2020-12-01 18:11 UTC, MichaelChirico commented
but rot is not exported right?

I was recently pointed to this when trying to test private functions:

https://softwareengineering.stackexchange.com/questions/100959/how-do-you-unit-test-private-methods

I'm happy to do so if our goal is 100% coverage, or if you can think of a
way to test it obliquely

On Mon, Nov 30, 2020, 12:04 PM AshesITR <notifications@github.com> wrote:

> *@AshesITR* requested changes on this pull request.
>
> Please add a test for rot() instead of # nocov
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jimhester/lintr/pull/629#pullrequestreview-541112192>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2BA5KD7PJAWODVGGR6HODSSPGC5ANCNFSM4UG24WVA>
> .
>