change cyclocomp_linter default argument to 15 (same as default_linters)
jimhester/lintr pull request #695
Opened 2020-12-06 20:50 UTC by AshesITR

fixes #693

2020-12-08 18:35 UTC, russHyde requested changes

2020-12-08 20:02 UTC, AshesITR commented on NEWS.md
> +* Set the default `complexity_limit` in `cyclocomp_linter` to 15. This is the same complexity limit that is enforced via
Should we do that for all of the linters with arguments then?

2020-12-09 09:53 UTC, russHyde commented on NEWS.md
> +* Set the default `complexity_limit` in `cyclocomp_linter` to 15. This is the same complexity limit that is enforced via
IMO yes. This way, when using `?default_linters` a user can be pointed to `?some_linter` to find out whatever default arguments are used by `some_linter` when part of `default_linters`.

Plus, it makes it more likely that the default arguments are modified in a single place when lintr is updated in the future.

2020-12-09 14:27 UTC, russHyde approved these changes
LGTM

2020-12-09 14:34 UTC, merged