Fix nolint cache
jimhester/lintr pull request #808
Opened 2021-06-03 15:11 UTC by renkun-ken

Closes #800 

If `find_new_line()` returns `NA` it means the content no longer matches the line, then the cached lints are dropped.

2021-06-04 19:52 UTC, AshesITR requested changes
It seems the test case misses the `return(NA)`line. Can you investigate?

2021-06-05 00:37 UTC, renkun-ken commented
Previously, the `return(NA)` lines could be triggered in the example at https://github.com/jimhester/lintr/issues/800#issue-892584344 where `find_new_line()` in the 2nd time of calling `lint` returns `NA` and the result is put into cache. The 3rd time of calling `lint` will retrieve the cached result and call `find_new_line()` with `line_number = NA`. 

```
> file <- tempfile()                                                                                                         

> cat("1+1\n", file = file)                                                                                                  

> lintr::lint(file, cache = TRUE)                                                                                            
/private/var/folders/8n/fdyp8ztd42gd2s61p6nzqrgh0000gn/T/Rtmpv4GEtV/file11bd747d8ebca:1:2: style: Put spaces around all infix operators.
1+1
~^~

> cat("1+1 # nolint\n", file = file)                                                                                         

> lintr::lint(file, cache = TRUE)                                                                                            
/private/var/folders/8n/fdyp8ztd42gd2s61p6nzqrgh0000gn/T/Rtmpv4GEtV/file11bd747d8ebca:NA:2: style: Put spaces around all infix operators.
1+1
~^~

> cat("1+1\n", file = file)                                                                                                  

> lintr::lint(file, cache = TRUE)                                                                                            
Error in if (low > 0L) { : missing value where TRUE/FALSE needed
Backtrace:
1: find_new_line(lint$line_number, unname(lint$line), lines)
2: FUN(X[[i]], ...)
3: lapply(lints, function(lint) {
4: retrieve_lint(lint_cache, expr, linter, source_expressions$lines)
5: lintr::lint(file, cache = TRUE)
```

This PR checks if `find_new_line()` with cached result returns `NA`, the cache will be dropped in the first place, and hence there's no change to call `find_new_line()` with `line_number = NA` anymore.

Therefore, the `return(NA)` line just works as a fallback so that whenever `line_number = NA` is supplied it will return `NA` rather than stop. Should we remove this line if there's no change to trigger it any more?

2021-06-05 02:02 UTC, renkun-ken commented
The `return(NA)` line is removed as not needed now.

2021-06-05 11:22 UTC, AshesITR approved these changes
LGTM, thanks!

2021-06-05 11:22 UTC, merged